export const PageNames = {
    DASHBOARD: "Dashboard",
    HOME_BANNER: "Home Banner",
    OBJECTIVE: "Objective",
    TESTIMONIAL: "Testimonial",
    INITIATIVES: "Initiatives",
    ACHIEVEMENTS: "Achievements",
    PHOTOS_GALLERY: "Photos Gallery",
    VIDEOS_GALLERY: "Videos Gallery",
    ADD_TRUST_BODIES: "Add Trust Bodies",
    TRUST_BODIES_LIST: "Trust Bodies List",
    ADD_NEWS_UPDATES: "Add News Updates",
    NEWS_UPDATES_LIST: "News Updates List",
    NEWS_LETTERS: "News Letters",
    ADD_BLOG: "Add Blog",
    BLOG_LIST: "Blog List",
    FAQ: "FAQ",
    ENQUIRY_LIST: "Enquiry List",
    SUPPORT_LIST: "Support List",
    ADD_MEMBER: "Add Member",
    MEMBER_LIST: "Member List",
    ADD_VOLUNTEER: "Add Volunteer",
    VOLUNTEER_LIST: "Volunteer List",
    ADD_DONATION: "Add Donation",
    DONATION_LIST: "Donation List",
    WEB_ENQUIRY: "Web Enquiry",
    DELEGATES: "Delegates",
    NEW_DATA: "New Data",
    WARM_DATA: "Warm Data",
    HOT_DATA: "Hot Data",
    COLD_DATA: "Cold Data",
    MASTER_DELEGATE_DATA: "Master Delegate Data",
    ADD_NEW_CONTESTANTS: "Add New Contestants",
    GENERAL_CONTESTANTS: "General Contestants",
    FOLLOW_UP_CONTESTANTS: "Follow UP Contestants",
    HOT_CONTESTANTS: "Hot Contestants",
    AUDITION_CONTESTANTS: "Audition Contestants",
    VIDEO_CONTESTANTS: "Video Contestants",
    FINALE_CONTESTANTS: "Finale Contestants",
    MASTER_CONTESTANTS: "Master Contestants",
    NOT_INTR_CONTESTANTS: "Not Intr. Contestants",
    ADD_RANGSHALA: "Add Rangshala",
    RANGSHALA_LIST: "Rangshala List",
    ADD_PAINTING: "Add Painting",
    PAINTING_LIST: "Painting List",
    ADD_NATAK: "Add Natak",
    NATAK_LIST: "Natak List",
    ADD_OCCUPATION: "Add Occupation",
    ADD_ORGANIZATION: "Add Organization",
    ADD_DESIGNATION: "Add Designation",
    ADD_DEPARTMENT: "Add Department",
    ADD_CATEGORY: "Add Category",
    ADD_PROFESSION: "Add Profession",
    ADD_EVENT: "Add Event",
    ADD_STATUS: "Add Status",
    ADD_UNIVERSITY: "Add University",
    ADD_SOURCE: "Add Source",
    ADD_ENQUIRY: "Add Enquiry",
    ADD_DATA: "Add Data",
    ADD_TARGET: "Add Target",
    ADD_PUBLISHED: "Add Published",
    ADD_COORDINATOR_STATUS: "Add Coordinator Status",
    ADD_BANK: "Add Bank",
    IMAGE_CATEGORY: "Image Category",
    ADD_IP: "Add IP",
    ADD_ROLE: "Add Role",
    ADD_USER: "Add User",
    ADD_COLLEGE: "Add College",
    COLLEGE_LIST: "College List",
    ROLE_RIGHTS: "Role Rights",
};