export const PAGES_LIST = [
  { name: "Home", path: "/" },
  { name: "About Us", path: "/about" },
  { name: "Initiatives", path: "/initiatives" },
  { name: "Upcoming Event", path: "/event/upcoming" },
  { name: "Past Event", path: "/event/past" },
  { name: "News Letters", path: "/communication/newsLetter" },
  { name: "Our Blog", path: "/communication/blog" },
  { name: "Resent Updates", path: "/communication/latestNews" },
  { name: "Photos Gallery", path: "/gallery/photos" },
  { name: "Video Gallery", path: "/gallery/videos"},
  { name: "Support Us", path: "/support" },
  { name: "Career", path: "/career" },
  { name: "Contact Us", path: "/contact" },
  { name: "Donate", path: "/donate" },
  { name: "Join As Volunteer", path: "/join/volunteer" },
  { name: "Become A Member", path: "/join/member" },
  { name: "Ann Sewa", path: "/ann-sewa" },
  { name: "Moksha Sewa", path: "/moksha-sewa" },
];
